FROM quay.io/hyperkineticnerd/minecraft:1.18.2-fabric

# USER minecraft
WORKDIR /minecraft
COPY files/shadowman/server.properties /minecraft/
COPY files/shadowman/eula.txt /minecraft/
COPY files/shadowman/mods/* /minecraft/mods/
COPY files/shadowman/datapacks/* /minecraft/world/datapacks/

EXPOSE 24454/udp
# WORKDIR /minecraft
