FROM registry.access.redhat.com/ubi8/ubi-minimal

USER root
RUN \
    microdnf --setopt=install_weak_deps=0 --setopt=keepcache=0 install java-17-openjdk-headless && \
    microdnf --setopt=install_weak_deps=0 --setopt=keepcache=0 install python3 && \
    microdnf clean all && \
    [ ! -d /var/cache/yum ] || rm -rf /var/cache/yum
